# Generated by Django 4.1.6 on 2023-02-08 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BdoWorldBossApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldboss',
            name='spawn_time',
        ),
    ]
