# Generated by Django 4.1.6 on 2023-02-08 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BdoWorldBossApi', '0002_remove_worldboss_spawn_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpawnTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BdoWorldBossApi.worldboss')),
            ],
        ),
    ]
