# Generated by Django 4.1.6 on 2023-02-08 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BdoWorldBossApi', '0003_spawntimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spawntimes',
            name='day',
            field=models.CharField(max_length=20),
        ),
    ]
